### PR TITLE
Templates for spag-rs

### PR DESCRIPTION
**Pull request by pglass**
~~Not ready for merge yet.~~
- [x] Needs some more test cases
- [x] Needs to let me disable the shortcut syntax if I want
- [x] Needs to avoid panicking if the environment isn't found with `[env].thing` syntax

### CODE REVIEW

**Comment by pglass** [comment]
Merge me @Squab. I squashed this because I screwed up the rebase and had to fix things.

The error messages are not great in a bunch of places. I didn't want to tests for grabbing stuff from envs (but this works) because I didn't want to read/write files in the unit tests, and since we'll test it later in the python tests

With this code as it is, you can `spag request "<untemplate-this>" --with key val --with mini wumbo` to test this out. This will not make request but will untemplate the text you pass to the request command. You should be able to do the following:

    $ spag env unset --everything
    ---
    {}
    $ spag env set mini wumbo
    ---
    "mini": "wumbo"
    $ spag env set a.b.c squidward
    ---
    "a":
      "b":
        "c": "squidward"
    "mini": "wumbo"
    $ spag request {{[].a.b.c}}
    key=[] val=[]
    untemplated: Ok("squidward")
    $ spag request {{[].mini}}
    key=[] val=[]
    untemplated: Ok("wumbo")
    $ spag request {{[].m}}
    key=[] val=[]
    untemplated: Err("substitution failed")
    $ spag request '{{a, [].m}}' --with a A
    key=["a"] val=["A"]
    untemplated: Ok("A")
    $ spag request '{{[].m, mini}}' --with mini wumbo
    key=["mini"] val=["wumbo"]
    untemplated: Ok("wumbo")
    $ spag request '@mini' --with mini wumbo
    key=["mini"] val=["wumbo"]
    untemplated: Ok("wumbo")
    $ spag request '@poo' --with mini wumbo
    key=["mini"] val=["wumbo"]
    untemplated: Err("substitution failed")
    $ spag request '@poo/things' --with poo wumbo
    key=["poo"] val=["wumbo"]
    untemplated: Ok("wumbo/things")
    $ spag request '@[].a.b.c/things'
    key=[] val=[]
    untemplated: Ok("squidward/things")

**Comment by Squab** [comment]
@pglass You still want to merge this wrt the conversations we had earlier about errors?

**Comment by pglass** [comment]
@Squab Let's see. So the untemplater requires at least some functions (like in `load_environment`)  to return the error message instead of panicking/terminating so that it can ignore the error and move on to try to substitute the next item in the template list.

Idk. I think I still prefer using `Result<>` as much as possible. Usually, we probably won't care and could just exit(1). But returning the error message via `Result<>` is more flexible and makes the code more reusable: e.g. I can decide when I terminate, rather that `load_file` or whatever terminating for me. And I can append to the error message or replace it or whatever to give better error messages. And then, testing for negative cases is easier when everything gives you back the error message.

We should still have an `error(msg)` function for the main module so we actually have the right exit codes. But it feels better to me if all of the supporting modules just return error messages.

**Comment by Squab** [comment]
I can get down with that. :+1:

**Pull request merged**
