### PR TITLE
Improve templates

### PR DESCRIPTION
**Pull request by pglass**
For requests, shortcuts work in `--with` values, in `-H` args, and in `--data` args.

Doesn't yet work with environment commands like `spag env set thing=@id`.

### CODE REVIEW

**Comment by Squab** [comment]
Looks like you might be running into doing `spag env set thing=multi word thing` also, you've got "Fix 44" as your title, but "resolves #43" in your commit msg.

**Comment by pglass** [comment]
This is dependent on https://github.com/pglbutt/noodles/pull/47, which resolves #43. Github just doesn't display dependent pull requests...

**Comment by pglass** [comment]
Okay, closed out #47 so we're tracking all the things here now.

* I updated the headers decorator to ensure our headers are always a dictionary coming out of that decorator, so we don't have to worry about it elsewhere. Also changed the entire decorator, so if that's not doing a thing it should be doing, let me know.
* Using spaces in environment vars works as long as you use quotes: `spag env set 'thing=space space space'`. This is done for us in `subprocess.call` or `Popen` or whatever.
* TODO: There's the issue you mentioned with environment headers overriding headers specified elsewhere. This seems to only happen when putting headers in the request file and not in `spag post` or `spag get` or whatever. I don't think is a result of this PR, but I need to look at it more.

**Comment by Squab** [comment]
This looks :+1: for the things you mentioned. I'm ready to merge it, unless you wanted to get those TODOs in this PR? I could help with those, if you don't.

**Comment by pglass** [comment]
You can merge if you want. I'm probably not spagging this weekend.

**Comment by pglass** [comment]
So I lied before. It actually does work with `spag env set`. I added tests for that.

**Comment by Squab** [comment]
:+1:

**Pull request merged**
